spring:
 datasource:
  url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12758167
  username: sql12758167
  password: srb1hVqSWM
 
 jpa:
  properties:
   hibernate.dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
   ddl-auto: update
  show-sql: false
