spring:
 datasource:
  url: jdbc:mysql://mysql.railway.internal:3306/railway
  username: root
  password: ZcEkJezIjcRqDEnuwLCTTvyPpHBtxnwH
 
 jpa:
  properties:
   hibernate.dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
   ddl-auto: update
  show-sql: false